set_xmakever("2.5.9")

add_requires("glfw", "spdlog")
add_rules("mode.release", "mode.debug")

target("vkext")
    set_kind("static")
    add_includedirs("src/vkext")
    add_files("src/vkext/*.cpp")
    add_packages("spdlog")
    on_load(function (target)
        target:add(find_packages("cmake::Vulkan"))
    end)

target("app")
    set_kind("static")
    add_includedirs("src/app", "src")
    add_files("src/app/*.cpp")
    add_deps("vkext")
    add_packages("glfw", "spdlog", {public=true})
    on_load(function (target)
        target:add(find_packages("cmake::Vulkan"))
    end)

target("RainEngine")
    set_kind("binary")
    add_includedirs("src/app")
    add_files("src/main.cpp")
    add_deps("app")
    set_targetdir("bin")
    on_load(function (target)
        target:add(find_packages("cmake::Vulkan"))
    end)