set_xmakever("2.5.9")

add_requires("glfw", "spdlog")
add_rules("mode.release", "mode.debug")
set_languages("cxx17")

target("engine")
    set_kind("static")
    add_includedirs("src/engine", "src")
    add_files("src/engine/*.cpp", "src/device/*.cpp", "src/vkext/*.cpp")
    add_packages("glfw", "spdlog", {public=true})
    on_load(function (target)
        target:add(find_packages("cmake::Vulkan"))
    end)

target("RainEngine")
    set_kind("binary")
    add_includedirs("src/engine", "src")
    add_files("src/main.cpp")
    add_deps("engine")
    set_targetdir("bin")
    on_load(function (target)
        target:add(find_packages("cmake::Vulkan"))
    end)